"""RED — narrow LIVE_QUARANTINED gateway authorization (Codex handoff
2026-08-18, bounded slice).

Part 3: LIVE_QUARANTINED may submit ONLY snapshot-bound remaining-leg
MTS_RELEASE / MTS_EXIT orders.  The snapshot binding is a per-order proof
generated by the monitor ONLY after a fresh broker-truth recheck (remaining
leg still present, released contract absent, session match, recovery
identity valid).  Entry / manual / OCO / generic cancel stay blocked; the
execution mode itself is never changed (no LIVE_READY unlock).

Fail-closed (zero submit): ambiguous identity, query failure, session
mismatch, duplicate pending, missing BBO, missing/absent proof, flat
terminal.
"""
from types import SimpleNamespace
from unittest.mock import patch

import pytest

from core.mode_transition import ExecutionContext, LiveOrderBlocked
from core.order_intent_gateway import OrderIntentGateway
from strategies.futures.monitor import FuturesMonitor


def _proof(strategy="MTS_RELEASE", contract="TMFI6", side="LONG",
           snapshot_hash="snap-hash-1"):
    return {"strategy": strategy, "contract": contract, "side": side,
            "qty": 1, "snapshot_hash": snapshot_hash,
            "recovery_order_id": "ORD-1", "session": "day"}


def _quarantined_ctx():
    return ExecutionContext(
        requested_mode="live", effective_mode="live_quarantined",
        live_order_allowed=False, audit_reasons=("BROKER_NOT_FLAT",))


def _order(strategy="MTS_RELEASE", proof=None, method="place_order"):
    o = SimpleNamespace(strategy=strategy, symbol="TMFI6",
                        side=SimpleNamespace(value="LONG"), quantity=1)
    if proof is not None:
        o.quarantine_exit_proof = proof
    return o


# ── ExecutionContext.assert_order_allowed ───────────────────────────────────

def test_quarantined_ctx_allows_snapshot_bound_release_exit():
    ctx = _quarantined_ctx()
    ctx.assert_order_allowed(
        _order(strategy="MTS_RELEASE", proof=_proof()), method="place_order")
    ctx.assert_order_allowed(
        _order(strategy="MTS_EXIT",
               proof=_proof(strategy="MTS_EXIT")), method="place_order")


def test_quarantined_ctx_blocks_entry_manual_oco_cancel():
    ctx = _quarantined_ctx()
    for o in (_order(strategy="MTS_ENTRY", proof=_proof()),
              _order(strategy="MTS_RELEASE_OCO", proof=_proof()),
              _order(strategy="MANUAL", proof=_proof()),
              _order(strategy="MTS_RELEASE", proof=_proof())):
        with pytest.raises(LiveOrderBlocked):
            ctx.assert_order_allowed(o, method="place_order")
    # generic cancel without proof blocked
    with pytest.raises(LiveOrderBlocked):
        ctx.assert_order_allowed(_order(strategy="MTS_RELEASE"),
                                 method="cancel_order")


def test_quarantined_exit_without_proof_blocked():
    ctx = _quarantined_ctx()
    with pytest.raises(LiveOrderBlocked):
        ctx.assert_order_allowed(_order(strategy="MTS_RELEASE"),
                                 method="place_order")


def test_quarantined_proof_invalid_blocked():
    ctx = _quarantined_ctx()
    for bad in ({}, _proof(strategy="MTS_ENTRY"),
                _proof(contract=""), _proof(snapshot_hash="")):
        with pytest.raises(LiveOrderBlocked):
            ctx.assert_order_allowed(
                _order(strategy="MTS_RELEASE", proof=bad),
                method="place_order")


def test_live_ready_ctx_unchanged():
    ctx = ExecutionContext(
        requested_mode="live", effective_mode="live_ready",
        live_order_allowed=True)
    ctx.assert_order_allowed(_order(strategy="MTS_ENTRY"),
                             method="place_order")  # no raise


# ── OrderIntentGateway.authorize_intent ─────────────────────────────────────

def test_gateway_authorize_quarantine_snapshot_bound_exit():
    gw = OrderIntentGateway()
    _ok, _binding, _reason = gw.authorize_intent(
        action="PARTIAL_EXIT", strategy="MTS_RELEASE",
        authority={"live": True, "mode": "live_quarantined",
                   "quarantine_exit_proof": _proof()})
    assert _ok is True and _reason is None
    assert _binding is not None and _binding.get("strategy") == "MTS_RELEASE"
    _ok, _binding, _reason = gw.authorize_intent(
        action="EXIT", strategy="MTS_EXIT",
        authority={"live": True, "mode": "live_quarantined",
                   "quarantine_exit_proof": _proof(strategy="MTS_EXIT")})
    assert _ok is True and _reason is None


def test_gateway_quarantine_without_proof_denied():
    gw = OrderIntentGateway()
    _ok, _binding, _reason = gw.authorize_intent(
        action="PARTIAL_EXIT", strategy="MTS_RELEASE",
        authority={"live": True, "mode": "live_quarantined"})
    assert _ok is False and _reason == "LIVE_ORDER_AUTHORIZATION_FAILED"
    # entry intent with a proof is still denied (proof is exit-scoped)
    _ok, _binding, _reason = gw.authorize_intent(
        action="SELL_NEAR_BUY_FAR", strategy="MTS_ENTRY",
        authority={"live": True, "mode": "live_quarantined",
                   "quarantine_exit_proof": _proof()})
    assert _ok is False and _reason == "LIVE_ORDER_AUTHORIZATION_FAILED"
    # OCO stays disabled
    _ok, _binding, _reason = gw.authorize_intent(
        action="PARTIAL_EXIT", strategy="MTS_RELEASE_OCO",
        authority={"live": True, "mode": "live_quarantined",
                   "quarantine_exit_proof": _proof()})
    assert _ok is False and _reason == "GATEWAY_OCO_DISABLED"


# ── monitor proof generator (pre-submit broker truth recheck) ───────────────

def _monitor_with_recovery(tmp_path):
    m = FuturesMonitor.__new__(FuturesMonitor)
    m.live_trading = True
    m.dry_run = False
    m.contract = SimpleNamespace(code="TMFH6")
    m.far_contract = SimpleNamespace(code="TMFI6")
    m._execution_context = SimpleNamespace(
        requested_mode="live", effective_mode="live_quarantined",
        session_id="sess-1", live_order_allowed=False)
    m.session_type = "day"
    m._live_broker_authority_at = 0.0
    m._broker_position_observed = True
    m._live_broker_flat_proven = False
    m._broker_authority_degraded = False
    m._reconcile_local_orders_from_snapshot = lambda snap: None
    m._persist_current_session_canonical = lambda snap: None
    m._write_live_session_upl = lambda pos, ctx: None
    return m


def _recovered_strategy():
    from strategies.plugins.futures.active.tmf_spread import TMFSpread
    s = TMFSpread.__new__(TMFSpread)
    s._has_position = True
    s._released_leg = "near"
    s._side = "LONG"
    s._trade_id = "mts-recovered-1"
    s._broker_recovery_source = "broker_reconciliation"
    s._broker_recovery_order_id = "ORD-1"
    s._broker_recovery_broker_order_id = "e8c20826"
    s._broker_recovery_snapshot_hash = "snap-hash-1"
    s._position_session_type = "day"
    return s


def _fresh_snap(released_present=False, capture="OK", session_id="sess-1"):
    positions = [{"account": "futures", "code": "TMFI6", "quantity": 1,
                  "direction": "Action.Buy", "avg_cost": 46058.0}]
    if released_present:
        positions.append({"account": "futures", "code": "TMFH6",
                          "quantity": 1, "direction": "Action.Sell",
                          "avg_cost": 45923.0})
    return {
        "fetch_status": {"capture": capture},
        "account_identity_hash": "acct-1",
        "canonical_input_hash": "snap-hash-1",
        "session_id": session_id,
        "positions": positions,
        "open_orders": [],
    }


def test_quarantine_exit_proof_requires_fresh_recheck(tmp_path):
    """The proof is generated ONLY when the FRESH snapshot still shows the
    remaining leg with the released contract absent + session match."""
    m = _monitor_with_recovery(tmp_path)
    m._capture_post_startup_snapshot = lambda: _fresh_snap()
    proof = m._mts_quarantine_exit_proof(
        _recovered_strategy(), "MTS_RELEASE", "PARTIAL_EXIT")
    assert proof is not None
    assert proof["strategy"] == "MTS_RELEASE"
    assert proof["contract"] == "TMFI6"
    assert proof["side"] == "LONG"
    assert proof["snapshot_hash"] == "snap-hash-1"


def test_quarantine_exit_proof_recheck_failure_fails_closed(tmp_path):
    m = _monitor_with_recovery(tmp_path)
    # released contract BACK at broker -> contradicts the recovery
    m._capture_post_startup_snapshot = lambda: _fresh_snap(released_present=True)
    assert m._mts_quarantine_exit_proof(
        _recovered_strategy(), "MTS_RELEASE", "PARTIAL_EXIT") is None
    # capture failure
    m._capture_post_startup_snapshot = lambda: _fresh_snap(capture="FAIL")
    assert m._mts_quarantine_exit_proof(
        _recovered_strategy(), "MTS_RELEASE", "PARTIAL_EXIT") is None
    # session mismatch
    m._capture_post_startup_snapshot = lambda: _fresh_snap(session_id="sess-old")
    assert m._mts_quarantine_exit_proof(
        _recovered_strategy(), "MTS_RELEASE", "PARTIAL_EXIT") is None


def test_quarantine_exit_proof_flat_terminal_fails_closed(tmp_path):
    """Flat terminal (no positions) -> no proof -> zero submit."""
    m = _monitor_with_recovery(tmp_path)
    m._capture_post_startup_snapshot = lambda: _fresh_snap()
    m._capture_post_startup_snapshot = lambda: {
        "fetch_status": {"capture": "OK"},
        "account_identity_hash": "acct-1",
        "canonical_input_hash": "snap-hash-2",
        "session_id": "sess-1",
        "positions": [],
        "open_orders": [],
    }
    assert m._mts_quarantine_exit_proof(
        _recovered_strategy(), "MTS_EXIT", "EXIT") is None


def test_quarantine_exit_proof_requires_recovery_identity(tmp_path):
    """No broker-reconciliation recovery marker -> no proof (a fill-based
    single leg in quarantine stays blocked)."""
    m = _monitor_with_recovery(tmp_path)
    m._capture_post_startup_snapshot = lambda: _fresh_snap()
    s = _recovered_strategy()
    del s._broker_recovery_source
    assert m._mts_quarantine_exit_proof(s, "MTS_RELEASE", "PARTIAL_EXIT") is None


# ── end-to-end: quarantined remaining-leg RELEASE via _submit_mts_order_signal

def _submit_monitor(tmp_path):
    m = _monitor_with_recovery(tmp_path)
    m.order_mgr = SimpleNamespace(active_orders={}, completed=[])
    m._capture_post_startup_snapshot = lambda: _fresh_snap()
    m._hydrate_exit_only_position = lambda: None
    m._leg_lock_enabled = lambda: False
    m._submit_via_gateway = lambda order, **kw: True
    m._gateway = lambda: OrderIntentGateway()
    m._record_gateway_intent = lambda *a, **kw: None
    return m


def test_quarantined_release_submits_with_proof(tmp_path):
    """Snapshot-bound remaining-leg MTS_RELEASE goes through in quarantine."""
    from strategies.plugins.futures.active.tmf_spread import TMFSpread
    m = _submit_monitor(tmp_path)
    s = _recovered_strategy()
    s._near_side = "SHORT"
    s._far_side = "LONG"
    signal = SimpleNamespace(action="PARTIAL_EXIT",
                             reason="RELEASE_NEAR: threshold")
    bar_dict = {"near_close": 45600.0, "far_close": 45900.0,
                "near_open": 45600.0, "near_high": 45650.0,
                "near_low": 45550.0, "far_open": 45900.0,
                "far_high": 45950.0, "far_low": 45850.0,
                "spread_z": 0.0}
    submitted = []
    m._submit_via_gateway = lambda order, **kw: submitted.append(order) or True
    with patch.object(m, "_append_mts_event"):
        m._submit_mts_order_signal(signal, s, bar_dict, "2026-08-18T08:00:00")
    assert len(submitted) == 1
    assert submitted[0].strategy == "MTS_RELEASE"
    assert submitted[0].symbol == "TMFH6"  # released near leg close order


def test_quarantined_release_without_proof_zero_submit(tmp_path):
    """No recovery identity -> proof None -> ORDER_INTENT_BLOCKED, zero
    submit."""
    from strategies.plugins.futures.active.tmf_spread import TMFSpread
    m = _submit_monitor(tmp_path)
    s = _recovered_strategy()
    del s._broker_recovery_source  # no recovery binding
    s._near_side = "SHORT"
    s._far_side = "LONG"
    signal = SimpleNamespace(action="PARTIAL_EXIT",
                             reason="RELEASE_NEAR: threshold")
    bar_dict = {"near_close": 45600.0, "far_close": 45900.0,
                "near_open": 45600.0, "near_high": 45650.0,
                "near_low": 45550.0, "far_open": 45900.0,
                "far_high": 45950.0, "far_low": 45850.0,
                "spread_z": 0.0}
    submitted = []
    m._submit_via_gateway = lambda order, **kw: submitted.append(order) or True
    events = []
    m._append_mts_event = lambda event, **kw: events.append(event)
    m._submit_mts_order_signal(signal, s, bar_dict, "2026-08-18T08:00:00")
    assert submitted == []
    assert "ORDER_INTENT_BLOCKED" in events
